"""
settings.py — Global configuration for the JESA DMAT application.

This module centralizes all application parameters:

BACKEND (Sections 1–6):

- File and directory paths (reference framework, assessment, outputs)
- Numerical precision (scores, DMI, TPI)
- Engine behavior (weight validation, missing scores)
- Logging configuration (console)

FRONTEND (Sections 7–11):

- Application metadata (name, version, author)
- Streamlit configuration (layout, sidebar, icons)
- Export configuration (PDF, Excel)
- Session and upload management
- Cache and debug parameters

Files are resolved through environment variables (backend)
and static paths (frontend). Use the global `settings` instance
to access all parameters.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from pathlib import Path
from typing import ClassVar


# ── Project root paths ──────────────────────────────────────────────────────

_ROOT_DIR = Path(__file__).resolve().parent.parent


# ============================================================================
# =========================== BACKEND SETTINGS ===============================
# ============================================================================


@dataclass(frozen=True)
class BackendSettings:
    """
    Backend configuration for JESA DMAT.

    All attributes are frozen after instantiation (frozen=True) to
    prevent accidental modifications during runtime.
    """

    # ========================================================================
    # 1. PROJECT PATHS (BACKEND)
    # ========================================================================

    # Expected structure:
    # JESA_DMAT/
    # ├── app.py
    # ├── config/
    # │   └── settings.py
    # ├── data/
    # ├── engines/
    # ├── pages/
    # └── outputs/

    BASE_DIR: Path = _ROOT_DIR
    """Root directory of the JESA_DMAT project."""

    DATA_DIR: Path = _ROOT_DIR / "data"
    """Directory containing data files (reference frameworks, assessments)."""

    ASSESSMENT_DIR: Path = _ROOT_DIR / "data" / "assessment"
    """Directory containing assessment files."""

    KNOWLEDGE_BASE_DIR: Path = _ROOT_DIR / "data" / "knowledge_base"
    """Directory containing the knowledge base (recommendations)."""

    # ========================================================================
    # 2. EXCEL FILES (BACKEND)
    # ========================================================================

    # JESA reference framework.
    # Contains: HIERARCHY, GENERIC_MATURITY_SCALE, INDICATORS,
    # INDICATOR_SCORING_GRIDS, QUESTIONNAIRE_TEMPLATE, etc.

    REFERENTIEL_FILE: Path = Path(
        os.environ.get(
            "JDMAF_REFERENTIEL_FILE",
            str(
                _ROOT_DIR
                / "data"
                / "knowledge_base"
                / "REFERENTIEL_GRILLES_MATURITE_DIGITALE_JESA.xlsx"
            ),
        )
    )

    # Knowledge base used by the decision engines:
    # recommendations, roadmap, dependencies, best practices, etc.

    RECOMMENDATIONS_FILE: Path = Path(
        os.environ.get(
            "JDMAF_RECOMMENDATIONS_FILE",
            str(
                _ROOT_DIR
                / "data"
                / "knowledge_base"
                / "BASE_CONNAISSANCES_RECOMMANDATIONS_JESA.xlsx"
            ),
        )
    )

    # Assessment file.
    # Contains assessment responses / scores.
    # In production, this file can be provided by the user.

    ASSESSMENT_FILE: Path = Path(
        os.environ.get(
            "JDMAF_ASSESSMENT_FILE",
            str(_ROOT_DIR / "data" / "assessment" / "assessment.xlsx"),
        )
    )

    # ========================================================================
    # 3. OUTPUT DIRECTORY (BACKEND)
    # ========================================================================

    # All files generated by the backend are grouped here.
    #
    # Example:
    # outputs/
    # ├── assessment_results.json
    # ├── assessment_report.pdf
    # └── assessment_export.xlsx

    OUTPUT_DIR: Path = Path(
        os.environ.get(
            "JDMAF_OUTPUT_DIR",
            str(_ROOT_DIR / "outputs"),
        )
    )

    # ========================================================================
    # 4. NUMERICAL PRECISION (BACKEND)
    # ========================================================================

    # Maturity scores: 0–5 scale.
    SCORE_DECIMAL_PRECISION: int = 3

    # DMI: score expressed as a percentage (e.g. 62.4%).
    DMI_DECIMAL_PRECISION: int = 1

    # TPI: index between 0 and 1.
    TPI_DECIMAL_PRECISION: int = 3

    # ========================================================================
    # 5. ENGINE BEHAVIOR (BACKEND)
    # ========================================================================

    # 5.1 Weight validation
    # True: an invalid weight sum raises an error.
    # False: the engine logs a warning and normalizes the weights.
    STRICT_WEIGHT_VALIDATION: bool = True

    # 5.2 Target level below current level
    # Allows a target level lower than the current level (intentional decision).
    ALLOW_TARGET_BELOW_CURRENT: bool = True

    # 5.3 Non-applicable indicators
    # Applicability = "Not applicable" excludes the indicator from the calculation.
    # The weights of the remaining elements are renormalized.
    RENORMALIZE_WEIGHTS_ON_NA: bool = True

    # 5.4 Missing score
    # Applicability = "Applicable" but Selected_Score is empty:
    # the assessment is considered incomplete.
    ALLOW_MISSING_SCORE_ON_APPLICABLE: bool = False

    # ========================================================================
    # 6. LOGGING (BACKEND)
    # ========================================================================

    LOG_LEVEL: str = os.environ.get(
        "JDMAF_LOG_LEVEL",
        "INFO",
    )

    def get_logger(self, name: str) -> logging.Logger:
        """
        Return a consistently configured backend logger.

        Args:
            name: Name of the calling module.

        Returns:
            Configured logging.Logger instance.
        """
        logger = logging.getLogger(name)

        if not logger.handlers:
            handler = logging.StreamHandler()
            handler.setFormatter(
                logging.Formatter(
                    "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
                )
            )
            logger.addHandler(handler)

        logger.setLevel(self.LOG_LEVEL)
        return logger


# ============================================================================
# =========================== FRONTEND SETTINGS ==============================
# ============================================================================


@dataclass(frozen=True)
class FrontendSettings:
    """
    User interface and export configuration for JESA DMAT.

    All attributes are frozen after instantiation (frozen=True) to
    prevent accidental modifications during runtime.
    """

    # ========================================================================
    # 7. APPLICATION METADATA (FRONTEND)
    # ========================================================================

    APP_NAME: str = "JESA DMAT"
    """Full application name."""

    APP_VERSION: str = "1.0.0"
    """Current application version (semver)."""

    APP_AUTHOR: str = "JESA"
    """Application author / development team."""

    APP_COMPANY: str = "JESA"
    """Company owning the tool."""

    APP_DESCRIPTION: str = (
        "Digital Maturity Assessment Tool "
        "based on the Industry 5.0 framework."
    )
    """Description displayed in the interface and exports."""

    # ========================================================================
    # 8. STREAMLIT CONFIGURATION (FRONTEND)
    # ========================================================================

    PAGE_TITLE: str = "JESA DMAT"
    """Web page title displayed in the browser tab."""

    PAGE_ICON: str = str(
        _ROOT_DIR / "assets" / "logo" / "jesa_logo.png"
    )
    """Page icon (path to the logo). An emoji can also be used."""

    LAYOUT: str = "wide"
    """Streamlit layout: 'centered' or 'wide'."""

    SIDEBAR_STATE: str = "expanded"
    """Initial sidebar state: 'auto', 'expanded', or 'collapsed'."""

    WIDE_MODE_MAX_WIDTH: int = 1400
    """Maximum content width in wide mode (px)."""

    # ========================================================================
    # 9. EXPORT DIRECTORIES (FRONTEND)
    # ========================================================================

    EXPORTS_DIR: Path = _ROOT_DIR / "exports"
    """Root directory for exports."""

    EXPORT_PDF_DIR: Path = _ROOT_DIR / "exports" / "pdf"
    """Directory for PDF exports."""

    EXPORT_EXCEL_DIR: Path = _ROOT_DIR / "exports" / "excel"
    """Directory for Excel exports."""

    EXPORT_REPORT_DIR: Path = _ROOT_DIR / "exports" / "report"
    """Directory for generated reports."""

    # ========================================================================
    # 10. STATIC RESOURCES (FRONTEND)
    # ========================================================================

    ASSETS_DIR: Path = _ROOT_DIR / "assets"
    """Directory containing static resources."""

    LOGO_DIR: Path = _ROOT_DIR / "assets" / "logo"
    """Directory containing logos."""

    IMAGES_DIR: Path = _ROOT_DIR / "assets" / "images"
    """Directory containing images (illustrations, diagrams)."""

    STYLES_DIR: Path = _ROOT_DIR / "assets" / "styles"
    """Directory containing CSS stylesheets."""

    UPLOAD_DIR: Path = _ROOT_DIR / "uploads"
    """Directory containing user-uploaded files."""

    # ========================================================================
    # 11. EXPORT CONFIGURATION (FRONTEND)
    # ========================================================================

    # 11.1 PDF

    PDF_PAGE_SIZE: str = "A4"
    """Page size for PDF reports."""

    PDF_ORIENTATION: str = "portrait"
    """PDF orientation: 'portrait' or 'landscape'."""

    PDF_MARGIN_TOP: float = 15.0
    PDF_MARGIN_BOTTOM: float = 15.0
    PDF_MARGIN_LEFT: float = 12.0
    PDF_MARGIN_RIGHT: float = 12.0

    PDF_FONT_FAMILY: str = "Inter"
    """Main font used in PDF reports."""

    PDF_FONT_SIZE_BODY: int = 10
    """Body text size in PDF reports."""

    # 11.2 Excel

    EXCEL_SHEET_OVERVIEW: str = "Overview"
    EXCEL_SHEET_DETAIL: str = "Detail by Pillar"
    EXCEL_TABLE_STYLE: str = "TableStyleMedium2"

    # ========================================================================
    # 12. CHART CONFIGURATION (FRONTEND)
    # ========================================================================

    PLOTLY_TEMPLATE: str = "plotly_white"
    """Default Plotly template."""

    PLOTLY_DISPLAY_MODE_BAR: bool = False
    """Display the Plotly mode bar."""

    # ========================================================================
    # 13. SESSION PERSISTENCE (FRONTEND)
    # ========================================================================

    SESSION_SAVE_ENABLED: bool = True
    """Enable automatic session saving."""

    SESSION_SAVE_DIR: Path = _ROOT_DIR / "data" / "sessions"
    """Directory containing saved sessions."""

    SESSION_SAVE_FORMAT: str = "json"
    """Session storage format."""

    # ========================================================================
    # 14. USER UPLOADS (FRONTEND)
    # ========================================================================

    UPLOAD_ENABLED: bool = False
    """Enable user file uploads."""

    UPLOAD_MAX_SIZE_MB: int = 50
    """Maximum uploaded file size (MB)."""

    UPLOAD_ALLOWED_EXTENSIONS: tuple[str, ...] = (
        "csv",
        "xlsx",
        "json",
    )
    """Allowed file extensions for uploads."""

    # ========================================================================
    # 15. APPLICATION LOGGING (FRONTEND)
    # ========================================================================

    LOG_ENABLED: bool = True
    """Enable event logging."""

    LOG_DIR: Path = _ROOT_DIR / "logs"
    """Directory containing log files."""

    LOG_FILENAME: str = "jesa_dmat.log"
    """Main log file name."""

    LOG_LEVEL_FRONTEND: str = "INFO"
    """Default log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)."""

    LOG_FORMAT: str = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    """Log entry format."""

    LOG_MAX_BYTES: int = 5 * 1024 * 1024  # 5 MB
    """Maximum log file size before rotation."""

    LOG_BACKUP_COUNT: int = 3
    """Number of backup log files to retain."""

    # ========================================================================
    # 16. DEBUG & DEVELOPMENT (FRONTEND)
    # ========================================================================

    DEBUG: bool = False
    """Debug mode (detailed error display)."""

    # ========================================================================
    # 17. SESSION PARAMETERS (FRONTEND)
    # ========================================================================

    SESSION_TIMEOUT_SECONDS: int = 3600
    """Streamlit session timeout (seconds)."""

    SESSION_STATE_KEYS: ClassVar[tuple[str, ...]] = (
        "selected_company",
        "assessment_data",
        "assessment_results",
        "dashboard_data",
        "gap_results",
        "recommendations",
        "decision_analysis",
        "roadmap",
        "export_settings",
        "current_step",
        "uploaded_file",
        "maturity_scores",
    )
    """Streamlit session state keys to preserve / initialize."""

    # ========================================================================
    # 18. CACHE PARAMETERS (FRONTEND)
    # ========================================================================

    CACHE_TTL_SECONDS: int = 600
    """Cache lifetime (seconds)."""

    CACHE_MAX_ENTRIES: int = 50
    """Maximum number of cache entries."""


# ── Single global instance ──────────────────────────────────────────────────


class Settings:
    """
    Global configuration for JESA DMAT.

    Combines backend and frontend configurations into a single instance.
    Use the global `settings` instance to access all parameters.
    """

    def __init__(self):
        self.backend = BackendSettings()
        self.frontend = FrontendSettings()

    def __setattr__(self, name, value):
        backend_fields = getattr(
            BackendSettings,
            "__dataclass_fields__",
            {},
        )

        frontend_fields = getattr(
            FrontendSettings,
            "__dataclass_fields__",
            {},
        )

        if name in {"backend", "frontend"}:
            object.__setattr__(self, name, value)
            return

        if name in backend_fields and "backend" in self.__dict__:
            object.__setattr__(
                self,
                "backend",
                self._replace_dataclass_value(
                    self.backend,
                    name,
                    value,
                ),
            )
            return

        if name in frontend_fields and "frontend" in self.__dict__:
            object.__setattr__(
                self,
                "frontend",
                self._replace_dataclass_value(
                    self.frontend,
                    name,
                    value,
                ),
            )
            return

        object.__setattr__(self, name, value)

    @staticmethod
    def _replace_dataclass_value(instance, name, value):
        from dataclasses import replace

        current = getattr(instance, name)

        if isinstance(current, Path) and not isinstance(value, Path):
            value = Path(value)

        return replace(instance, **{name: value})

    # ========================================================================
    # Backend attribute delegation
    # ========================================================================

    @property
    def BASE_DIR(self) -> Path:
        return self.backend.BASE_DIR

    @property
    def DATA_DIR(self) -> Path:
        return self.backend.DATA_DIR

    @property
    def ASSESSMENT_DIR(self) -> Path:
        return self.backend.ASSESSMENT_DIR

    @property
    def KNOWLEDGE_BASE_DIR(self) -> Path:
        return self.backend.KNOWLEDGE_BASE_DIR

    @property
    def REFERENTIEL_FILE(self) -> Path:
        return self.backend.REFERENTIEL_FILE

    @property
    def RECOMMENDATIONS_FILE(self) -> Path:
        return self.backend.RECOMMENDATIONS_FILE

    @property
    def ASSESSMENT_FILE(self) -> Path:
        return self.backend.ASSESSMENT_FILE

    @property
    def OUTPUT_DIR(self) -> Path:
        return self.backend.OUTPUT_DIR

    @property
    def SCORE_DECIMAL_PRECISION(self) -> int:
        return self.backend.SCORE_DECIMAL_PRECISION

    @property
    def DMI_DECIMAL_PRECISION(self) -> int:
        return self.backend.DMI_DECIMAL_PRECISION

    @property
    def TPI_DECIMAL_PRECISION(self) -> int:
        return self.backend.TPI_DECIMAL_PRECISION

    @property
    def STRICT_WEIGHT_VALIDATION(self) -> bool:
        return self.backend.STRICT_WEIGHT_VALIDATION

    @property
    def ALLOW_TARGET_BELOW_CURRENT(self) -> bool:
        return self.backend.ALLOW_TARGET_BELOW_CURRENT

    @property
    def RENORMALIZE_WEIGHTS_ON_NA(self) -> bool:
        return self.backend.RENORMALIZE_WEIGHTS_ON_NA

    @property
    def ALLOW_MISSING_SCORE_ON_APPLICABLE(self) -> bool:
        return self.backend.ALLOW_MISSING_SCORE_ON_APPLICABLE

    @property
    def LOG_LEVEL(self) -> str:
        return self.backend.LOG_LEVEL

    def get_logger(self, name: str) -> logging.Logger:
        """Delegate to BackendSettings.get_logger."""
        return self.backend.get_logger(name)

    # ========================================================================
    # Frontend attribute delegation
    # ========================================================================

    @property
    def APP_NAME(self) -> str:
        return self.frontend.APP_NAME

    @property
    def APP_VERSION(self) -> str:
        return self.frontend.APP_VERSION

    @property
    def APP_AUTHOR(self) -> str:
        return self.frontend.APP_AUTHOR

    @property
    def APP_COMPANY(self) -> str:
        return self.frontend.APP_COMPANY

    @property
    def APP_DESCRIPTION(self) -> str:
        return self.frontend.APP_DESCRIPTION

    @property
    def PAGE_TITLE(self) -> str:
        return self.frontend.PAGE_TITLE

    @property
    def PAGE_ICON(self) -> str:
        return self.frontend.PAGE_ICON

    @property
    def LAYOUT(self) -> str:
        return self.frontend.LAYOUT

    @property
    def SIDEBAR_STATE(self) -> str:
        return self.frontend.SIDEBAR_STATE

    @property
    def WIDE_MODE_MAX_WIDTH(self) -> int:
        return self.frontend.WIDE_MODE_MAX_WIDTH

    @property
    def EXPORTS_DIR(self) -> Path:
        return self.frontend.EXPORTS_DIR

    @property
    def EXPORT_PDF_DIR(self) -> Path:
        return self.frontend.EXPORT_PDF_DIR

    @property
    def EXPORT_EXCEL_DIR(self) -> Path:
        return self.frontend.EXPORT_EXCEL_DIR

    @property
    def EXPORT_REPORT_DIR(self) -> Path:
        return self.frontend.EXPORT_REPORT_DIR

    @property
    def ASSETS_DIR(self) -> Path:
        return self.frontend.ASSETS_DIR

    @property
    def LOGO_DIR(self) -> Path:
        return self.frontend.LOGO_DIR

    @property
    def IMAGES_DIR(self) -> Path:
        return self.frontend.IMAGES_DIR

    @property
    def STYLES_DIR(self) -> Path:
        return self.frontend.STYLES_DIR

    @property
    def UPLOAD_DIR(self) -> Path:
        return self.frontend.UPLOAD_DIR

    @property
    def PDF_PAGE_SIZE(self) -> str:
        return self.frontend.PDF_PAGE_SIZE

    @property
    def PDF_ORIENTATION(self) -> str:
        return self.frontend.PDF_ORIENTATION

    @property
    def PDF_MARGIN_TOP(self) -> float:
        return self.frontend.PDF_MARGIN_TOP

    @property
    def PDF_MARGIN_BOTTOM(self) -> float:
        return self.frontend.PDF_MARGIN_BOTTOM

    @property
    def PDF_MARGIN_LEFT(self) -> float:
        return self.frontend.PDF_MARGIN_LEFT

    @property
    def PDF_MARGIN_RIGHT(self) -> float:
        return self.frontend.PDF_MARGIN_RIGHT

    @property
    def PDF_FONT_FAMILY(self) -> str:
        return self.frontend.PDF_FONT_FAMILY

    @property
    def PDF_FONT_SIZE_BODY(self) -> int:
        return self.frontend.PDF_FONT_SIZE_BODY

    @property
    def EXCEL_SHEET_OVERVIEW(self) -> str:
        return self.frontend.EXCEL_SHEET_OVERVIEW

    @property
    def EXCEL_SHEET_DETAIL(self) -> str:
        return self.frontend.EXCEL_SHEET_DETAIL

    @property
    def EXCEL_TABLE_STYLE(self) -> str:
        return self.frontend.EXCEL_TABLE_STYLE

    @property
    def PLOTLY_TEMPLATE(self) -> str:
        return self.frontend.PLOTLY_TEMPLATE

    @property
    def PLOTLY_DISPLAY_MODE_BAR(self) -> bool:
        return self.frontend.PLOTLY_DISPLAY_MODE_BAR

    @property
    def SESSION_SAVE_ENABLED(self) -> bool:
        return self.frontend.SESSION_SAVE_ENABLED

    @property
    def SESSION_SAVE_DIR(self) -> Path:
        return self.frontend.SESSION_SAVE_DIR

    @property
    def SESSION_SAVE_FORMAT(self) -> str:
        return self.frontend.SESSION_SAVE_FORMAT

    @property
    def UPLOAD_ENABLED(self) -> bool:
        return self.frontend.UPLOAD_ENABLED

    @property
    def UPLOAD_MAX_SIZE_MB(self) -> int:
        return self.frontend.UPLOAD_MAX_SIZE_MB

    @property
    def UPLOAD_ALLOWED_EXTENSIONS(self) -> tuple[str, ...]:
        return self.frontend.UPLOAD_ALLOWED_EXTENSIONS

    @property
    def LOG_ENABLED(self) -> bool:
        return self.frontend.LOG_ENABLED

    @property
    def LOG_DIR(self) -> Path:
        return self.frontend.LOG_DIR

    @property
    def LOG_FILENAME(self) -> str:
        return self.frontend.LOG_FILENAME

    @property
    def LOG_LEVEL_FRONTEND(self) -> str:
        return self.frontend.LOG_LEVEL_FRONTEND

    @property
    def LOG_FORMAT(self) -> str:
        return self.frontend.LOG_FORMAT

    @property
    def LOG_MAX_BYTES(self) -> int:
        return self.frontend.LOG_MAX_BYTES

    @property
    def LOG_BACKUP_COUNT(self) -> int:
        return self.frontend.LOG_BACKUP_COUNT

    @property
    def DEBUG(self) -> bool:
        return self.frontend.DEBUG

    @property
    def SESSION_TIMEOUT_SECONDS(self) -> int:
        return self.frontend.SESSION_TIMEOUT_SECONDS

    @property
    def SESSION_STATE_KEYS(self) -> tuple[str, ...]:
        return self.frontend.SESSION_STATE_KEYS

    @property
    def CACHE_TTL_SECONDS(self) -> int:
        return self.frontend.CACHE_TTL_SECONDS

    @property
    def CACHE_MAX_ENTRIES(self) -> int:
        return self.frontend.CACHE_MAX_ENTRIES


# ── Single global instance ──────────────────────────────────────────────────

settings = Settings()


# ============================================================================
# END OF MODULE
# ============================================================================