"""
Transformation Roadmap for JESA DMAT.

Displays the prioritized transformation actions generated by the backend
and provides export options for the completed assessment.
"""

from __future__ import annotations

from pathlib import Path
from html import escape

import streamlit as st

from components import render_footer, render_header
from utils.assessment_service import export_selected_assessment


# ==============================================================================
# CONFIGURATION
# ==============================================================================

PRIORITY_STYLES = {
    "Critical": "var(--dmat-danger)",
    "High": "var(--dmat-warning)",
    "Medium": "var(--dmat-muted)",
    "Low": "var(--dmat-muted)",
    "Very Low": "var(--dmat-muted)",
}

DEFAULT_PRIORITY_STYLE = "var(--dmat-muted)"


# ==============================================================================
# DATA
# ==============================================================================

def _get_roadmap_data() -> dict | None:
    """Return roadmap results stored in session state."""
    return st.session_state.get("roadmap_results")


def _get_priority_style(priority: str) -> str:
    """Return the visual color associated with a priority level."""
    return PRIORITY_STYLES.get(
        priority,
        DEFAULT_PRIORITY_STYLE,
    )


# ==============================================================================
# EXECUTIVE SUMMARY
# ==============================================================================

def _render_executive_summary(data: dict) -> None:
    """Display roadmap KPIs."""

    summary = data.get("summary", {})
    actions = data.get("prioritized_actions", [])

    critical_count = sum(
        1 for action in actions
        if action.get("priority_level") == "Critical"
    )

    high_count = sum(
        1 for action in actions
        if action.get("priority_level") == "High"
    )

    medium_count = sum(
        1 for action in actions
        if action.get("priority_level") == "Medium"
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        dmi = summary.get("dmi")
        st.metric(
            "DIGITAL MATURITY INDEX",
            f"{dmi:.1f}%" if dmi is not None else "—",
        )

    with col2:
        maturity = summary.get("maturity_level")
        st.metric(
            "MATURITY LEVEL",
            str(maturity).upper() if maturity else "—",
        )

    with col3:
        st.metric(
            "TRANSFORMATION ACTIONS",
            str(len(actions)),
        )

    with col4:
        top_priority = (
            actions[0].get("priority_level")
            if actions
            else None
        )

        st.metric(
            "TOP PRIORITY",
            str(top_priority).upper()
            if top_priority
            else "—",
        )

    if actions:
        st.caption(
            f"{critical_count} Critical · "
            f"{high_count} High · "
            f"{medium_count} Medium"
        )


# ==============================================================================
# PRIORITIZATION OVERVIEW
# ==============================================================================

def _render_prioritization_overview(data: dict) -> None:
    """Display prioritized transformation actions."""

    actions = data.get("prioritized_actions", [])

    st.markdown("## Prioritization Overview")
    st.caption(
        "Transformation opportunities ranked according to their priority index."
    )

    for action in actions:

        rank = action.get("rank", "—")
        title = escape(str(action.get("title", "Untitled action")))
        dimension = escape(str(action.get("dimension", "—")))
        priority = str(action.get("priority_level", "—"))
        phase = escape(str(action.get("phase", "—")))

        tpi = action.get("tpi", 0)

        try:
            tpi_value = float(tpi)
        except (TypeError, ValueError):
            tpi_value = 0.0

        tpi_value = max(0.0, min(100.0, tpi_value))

        priority_color = _get_priority_style(priority)

        with st.container(border=True):
            col_main, col_tpi = st.columns([4, 1])

            with col_main:
                st.caption(f"#{rank} · {dimension}")
                st.markdown(f"**{title}**")
                st.caption(phase)

            with col_tpi:
                st.markdown(
                    f"<div style='text-align:right;'>"
                    f"<span style='font-size:1.45rem;font-weight:700;'>{tpi_value:.1f}</span><br>"
                    f"<span style='font-size:0.72rem;color:gray;'>TPI</span>"
                    f"</div>",
                    unsafe_allow_html=True,
                )

            badge_html = (
                f"<span style='background:{priority_color};color:white;"
                f"padding:0.22rem 0.65rem;border-radius:999px;"
                f"font-size:0.7rem;font-weight:700;'>"
                f"{escape(priority.upper())}</span>"
            )

            bar_html = (
                f"<div style='width:100%;height:6px;background:#e0e0e0;"
                f"border-radius:999px;overflow:hidden;margin-top:0.5rem;'>"
                f"<div style='width:{tpi_value:.0f}%;height:100%;"
                f"background:{priority_color};border-radius:999px;'>"
                f"</div></div>"
            )

            st.markdown(badge_html + bar_html, unsafe_allow_html=True)


# ==============================================================================
# ACTION DETAILS
# ==============================================================================

def _render_action_details(data: dict) -> None:
    """Display detailed information for every transformation action."""

    actions = data.get("prioritized_actions", [])

    st.markdown("## Transformation Action Details")
    st.caption(
        "Review the rationale and implementation information for each action."
    )

    for action in actions:

        rank = action.get("rank", "—")
        title = str(action.get("title", "Untitled action"))
        tpi = action.get("tpi", 0)

        try:
            tpi_value = float(tpi)
        except (TypeError, ValueError):
            tpi_value = 0.0

        with st.expander(
            f"#{rank} · {title} · TPI {tpi_value:.1f}",
            expanded=False,
        ):

            col1, col2 = st.columns(2)

            with col1:
                st.markdown("**Dimension**")
                st.write(action.get("dimension", "—"))

                st.markdown("**Priority**")
                st.write(action.get("priority_level", "—"))

            with col2:
                st.markdown("**TPI**")
                st.write(f"{tpi_value:.1f} / 100")

                st.markdown("**Phase**")
                st.write(action.get("phase", "—"))

            st.divider()

            description = action.get("description")
            objective = action.get("objective")
            benefit = action.get("expected_benefit")
            implementation = action.get("implementation_note")

            if description:
                st.markdown("**Description**")
                st.write(description)

            if objective:
                st.markdown("**Objective**")
                st.write(objective)

            if benefit:
                st.markdown("**Expected Benefit**")
                st.write(benefit)

            if implementation:
                st.markdown("**Implementation Note**")
                st.write(implementation)


# ==============================================================================
# STRATEGIC SYNTHESIS
# ==============================================================================

def _render_strategic_synthesis(data: dict) -> None:
    """Display the strategic synthesis when provided by the backend."""

    strategic_summary = data.get("strategic_summary")

    if not strategic_summary:
        return

    st.markdown("## Executive Takeaway")

    st.info(str(strategic_summary))


# ==============================================================================
# EXPORT
# ==============================================================================

def _render_export_section() -> None:
    """
    Display export format selection and download buttons.

    CORRECTION : layout fixe en 3 colonnes + type="primary" pour éviter
    le rendu "blanc sur blanc" des boutons de download.
    """

    st.markdown("## Export Assessment")

    st.caption(
        "Select the deliverables you want to generate for this assessment."
    )

    backend_results = st.session_state.get("backend_results")

    if not backend_results:
        st.warning(
            "No assessment data is available for export."
        )
        return

    selected_formats = st.multiselect(
        "Export formats",
        options=["pdf", "excel", "report"],
        default=["pdf"],
        format_func=lambda value: {
            "pdf": "PDF Report",
            "excel": "Excel Workbook",
            "report": "Management Report",
        }.get(value, value.upper()),
        key="roadmap_export_formats",
    )

    if not selected_formats:
        st.info(
            "Select at least one export format."
        )
        return

    if st.button(
        "GENERATE SELECTED EXPORTS",
        key="generate_roadmap_exports",
        use_container_width=True,
        type="primary",
    ):

        try:

            export_paths = export_selected_assessment(
                backend_results,
                selected_formats,
            )

            st.session_state["latest_export_paths"] = {
                key: str(path)
                for key, path in export_paths.items()
            }

            st.success(
                "Selected export files generated successfully."
            )

            st.rerun()

        except Exception as exc:

            st.error(
                f"Export generation failed: {exc}"
            )

    export_paths = st.session_state.get(
        "latest_export_paths",
        {},
    )

    if not export_paths:
        return

    st.markdown("### Available Downloads")

    # ═══════════════════════════════════════════════════════════════
    # CORRECTION : layout fixe en 3 colonnes + type="primary"
    # pour éviter le rendu "blanc sur blanc" des boutons de download.
    # ═══════════════════════════════════════════════════════════════
    cols = st.columns(3)

    format_meta = {
        "pdf": (
            "DOWNLOAD Scoring Report",
            "application/pdf",
            "pdf",
        ),
        "excel": (
            "DOWNLOAD EXCEL",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "xlsx",
        ),
        "report": (
            "DOWNLOAD Global Report",
            "application/pdf",
            "pdf",
        ),
    }

    assessment_id = (
        backend_results.get("assessment_id")
        or "assessment"
    )

    for idx, (fmt_key, (label, mime, ext)) in enumerate(
        format_meta.items()
    ):

        path = export_paths.get(fmt_key)

        with cols[idx]:

            if not path:
                st.caption(
                    f"— {label} not generated —"
                )
                continue

            path_obj = Path(path)

            if not path_obj.exists():
                st.warning(
                    f"{label}: file missing"
                )
                continue

            try:
                file_data = path_obj.read_bytes()
                if len(file_data) == 0:
                    st.warning(
                        f"{label}: empty file"
                    )
                    continue
            except Exception:
                st.error(
                    f"{label}: read error"
                )
                continue

            filename = (
                f"JESA_DMAT_{assessment_id}.{ext}"
            )

            st.download_button(
                label=label,
                data=file_data,
                file_name=filename,
                mime=mime,
                key=f"roadmap_dl_{fmt_key}",
                use_container_width=True,
                type="primary",
            )


# ==============================================================================
# NAVIGATION
# ==============================================================================

def _render_navigation() -> None:
    """Display navigation buttons."""

    st.divider()

    col1, col2, col3 = st.columns(3)

    with col1:

        if st.button(
            "← BACK TO DASHBOARD",
            key="back_dashboard",
            use_container_width=True,
        ):
            st.switch_page(
                "pages/3_Dashboard.py"
            )

    with col2:

        if st.button(
            "START NEW ASSESSMENT",
            key="new_assessment",
            use_container_width=True,
        ):
            st.switch_page(
                "pages/2_New_Assessment.py"
            )

    with col3:

        if st.button(
            "BACK TO HOME",
            key="back_home",
            use_container_width=True,
        ):
            st.switch_page(
                "pages/1_Home.py"
            )


# ==============================================================================
# PAGE
# ==============================================================================

render_header(
    title="TRANSFORMATION ROADMAP",
    subtitle="Prioritized transformation actions for the industrial site",
    align="center",
    compact=False,
)


data = _get_roadmap_data()


# ==============================================================================
# EMPTY STATE
# ==============================================================================

if not data or not data.get("prioritized_actions"):

    st.warning(
        "No prioritization results are currently available. "
        "Complete the Decision Analysis step first."
    )

    _render_navigation()

    render_footer(
        product_name="JESA DMAT",
        version="v1.0.0",
        organization="JESA · ENSAM Casablanca",
        tagline="Internship Project · Digital Transformation & Industry 5.0",
        links=[
            {
                "label": "JESA",
                "url": "https://www.jesa.ma",
            },
            {
                "label": "ENSAM Casablanca",
                "url": "https://ensam-casablanca.ma",
            },
        ],
        align="center",
        compact=False,
        show_divider=True,
    )

    st.stop()


# ==============================================================================
# CONTENT
# ==============================================================================

_render_executive_summary(data)

st.divider()

_render_prioritization_overview(data)

st.divider()

_render_action_details(data)

st.divider()

_render_strategic_synthesis(data)

st.divider()

_render_export_section()

_render_navigation()


# ==============================================================================
# FOOTER
# ==============================================================================

render_footer(
    product_name="JESA DMAT",
    version="v1.0.0",
    organization="JESA · ENSAM Casablanca",
    tagline="Internship Project · Digital Transformation & Industry 5.0",
    links=[
        {
            "label": "JESA",
            "url": "https://www.jesa.ma",
        },
        {
            "label": "ENSAM Casablanca",
            "url": "https://ensam-casablanca.ma",
        },
    ],
    align="center",
    compact=False,
    show_divider=True,
)