# pages/5_Roadmap.py
"""
Transformation Roadmap for JESA DMAT – Prioritized actions for industrial digital transformation.
"""

from __future__ import annotations

import streamlit as st
from html import escape

from components import render_footer, render_header
from utils.assessment_service import export_selected_assessment


# ------------------------------------------------------------------------------
# CONFIGURATION – priority style mapping (backend-driven)
# ------------------------------------------------------------------------------
PRIORITY_STYLES = {
    "Critical": "var(--dmat-danger)",
    "High": "var(--dmat-warning)",
    "Medium": "var(--dmat-muted)",
    "Low": "var(--dmat-muted)",
}
# Fallback style for unknown priority
DEFAULT_PRIORITY_STYLE = "var(--dmat-muted)"


# ------------------------------------------------------------------------------
# DATA ADAPTER
# ------------------------------------------------------------------------------
def _get_roadmap_data() -> dict | None:
    """
    Retrieve roadmap results generated by the backend.

    In production, this function reads from session state where the backend
    stores the TPI results after the Decision Analysis step.
    If no results are available, it returns None (empty state).
    """
    # Real backend results (set by Decision Analysis page)
    return st.session_state.get("roadmap_results")


def _get_priority_style(priority: str) -> str:
    """Return the CSS color for the given priority level."""
    return PRIORITY_STYLES.get(priority, DEFAULT_PRIORITY_STYLE)


# ------------------------------------------------------------------------------
# RENDERING HELPERS
# ------------------------------------------------------------------------------

def _render_executive_summary(data: dict) -> None:
    """Render the executive decision summary (KPI strip)."""
    summary = data["summary"]
    actions = data["prioritized_actions"]
    critical_count = sum(1 for a in actions if a["priority_level"] == "Critical")
    high_count = sum(1 for a in actions if a["priority_level"] == "High")
    medium_count = sum(1 for a in actions if a["priority_level"] == "Medium")

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("DMI", f"{summary['dmi']:.1f}%")
    with col2:
        st.metric("MATURITY", summary["maturity_level"].upper())
    with col3:
        st.metric("ACTIONS", f"{len(actions)}")
    with col4:
        top_priority = actions[0]["priority_level"] if actions else "—"
        st.metric("TOP PRIORITY", top_priority.upper())

    if actions:
        st.caption(
            f"⚡ {critical_count} Critical · {high_count} High · {medium_count} Medium"
        )


def _render_prioritization_overview(data: dict) -> None:
    """Render the list of prioritized actions with TPI, priority badges, and phase."""
    actions = data["prioritized_actions"]
    st.markdown("## Prioritization Overview")

    for action in actions:
        rank = action["rank"]
        title = escape(str(action["title"]))
        dimension = escape(str(action["dimension"]))
        tpi = action["tpi"]
        priority = escape(str(action["priority_level"]))
        phase = escape(str(action.get("phase", "")))
        badge_color = _get_priority_style(action["priority_level"])

        st.markdown(
            f"""
            <div class="dmat-card" style="margin-bottom: 1rem;">
                <div style="display: flex; justify-content: space-between; align-items: center;">
                    <div>
                        <div style="font-size: 0.9rem; color: var(--dmat-muted);">
                            #{rank} · {dimension}
                        </div>
                        <div style="font-size: 1.2rem; font-weight: 600;">
                            {title}
                        </div>
                        <div style="font-size: 0.8rem; color: var(--dmat-muted); margin-top: 0.25rem;">
                            {phase}
                        </div>
                    </div>
                    <div style="text-align: right;">
                        <div style="font-size: 1.5rem; font-weight: 700;">
                            {tpi:.1f}
                        </div>
                        <div style="font-size: 0.75rem; color: var(--dmat-muted);">
                            TPI
                        </div>
                    </div>
                </div>
                <div style="margin-top: 0.5rem; display: flex; gap: 0.5rem;">
                    <span style="background: {badge_color}; color: white; padding: 0.1rem 0.6rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600;">
                        {priority}
                    </span>
                </div>
                <div style="margin-top: 0.5rem;">
                    <div style="background: var(--dmat-border); border-radius: 4px; height: 6px; width: 100%;">
                        <div style="background: {badge_color}; height: 6px; border-radius: 4px; width: {tpi:.0f}%;"></div>
                    </div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )


def _render_action_details(data: dict) -> None:
    """Render expandable sections with detailed information for each action."""
    actions = data["prioritized_actions"]
    st.markdown("## Transformation Action Details")

    for action in actions:
        title = escape(str(action["title"]))
        rank = action["rank"]
        tpi = action["tpi"]
        with st.expander(
            f"#{rank} – {title} (TPI: {tpi:.1f})",
            expanded=False,
        ):
            st.markdown(f"**Dimension:** {escape(str(action.get('dimension', '—')))}")
            st.markdown(f"**Priority:** {escape(str(action.get('priority_level', '—')))}")
            st.markdown(f"**TPI:** {tpi:.1f} / 100")
            st.markdown(f"**Phase:** {escape(str(action.get('phase', '—')))}")
            st.markdown("---")
            if action.get("description"):
                st.markdown(f"**Description:** {escape(str(action['description']))}")
            if action.get("objective"):
                st.markdown(f"**Objective:** {escape(str(action['objective']))}")
            if action.get("expected_benefit"):
                st.markdown(f"**Expected Benefit:** {escape(str(action['expected_benefit']))}")
            if action.get("implementation_note"):
                st.markdown(f"**Implementation Note:** {escape(str(action['implementation_note']))}")


def _render_strategic_synthesis(data: dict) -> None:
    """Render the strategic summary if provided."""
    if "strategic_summary" in data and data["strategic_summary"]:
        st.markdown("## Executive Takeaway")
        st.info(escape(str(data["strategic_summary"])))


def _render_export_section(data: dict) -> None:
    """Render export buttons with real data when export service is available."""
    st.markdown("## Export Options")
    col1, col2 = st.columns(2)

    backend_results = st.session_state.get("backend_results")
    if not backend_results:
        st.info("Load an assessment before exporting.")
        return

    if st.button("PREPARE EXPORT FILES", key="prepare_roadmap_exports"):
        try:
            export_paths = export_selected_assessment(backend_results, ["pdf", "excel"])
            st.session_state["latest_export_paths"] = {
                key: str(path) for key, path in export_paths.items()
            }
            st.success("Export files prepared.")
        except Exception as exc:
            st.error(f"Export generation failed: {exc}")

    export_paths = st.session_state.get("latest_export_paths", {})

    with col1:
        pdf_path = export_paths.get("pdf")
        if pdf_path:
            with open(pdf_path, "rb") as file:
                st.download_button(
                    label="EXPORT PDF",
                    data=file.read(),
                    file_name="JESA_DMAT_Report.pdf",
                    mime="application/pdf",
                )
    with col2:
        excel_path = export_paths.get("excel")
        if excel_path:
            with open(excel_path, "rb") as file:
                st.download_button(
                    label="EXPORT EXCEL",
                    data=file.read(),
                    file_name="JESA_DMAT_Report.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                )


def _render_navigation() -> None:
    """Render navigation buttons back to Dashboard and Home."""
    st.markdown("---")
    col1, col2, col3 = st.columns([1, 1, 1])
    with col1:
        if st.button("← BACK TO DASHBOARD", key="back_dashboard", use_container_width=True):
            st.switch_page("pages/3_Dashboard.py")
    with col3:
        if st.button("BACK TO HOME", key="back_home", use_container_width=True):
            st.switch_page("pages/1_Home.py")


# ------------------------------------------------------------------------------
# PAGE CONTENT
# ------------------------------------------------------------------------------

# Page header
render_header(
    title="TRANSFORMATION ROADMAP",
    subtitle="Prioritized transformation actions for the industrial site",
    align="center",
    compact=False,
)

# Retrieve real data from session state
data = _get_roadmap_data()

# Empty state
if not data or not data.get("prioritized_actions"):
    st.warning(
        "No prioritization results are currently available.\n\n"
        "Complete the Decision Analysis step first."
    )
    render_footer(
        product_name="JESA DMAT",
        version="v1.0.0",
        organization="JESA · ENSAM Casablanca",
        tagline="Internship Project · Digital Transformation & Industry 5.0",
        links=[
            {"label": "JESA", "url": "https://www.jesa.ma"},
            {"label": "ENSAM Casablanca", "url": "https://ensam-casablanca.ma"},
        ],
        align="center",
        compact=False,
        show_divider=True,
    )
    st.stop()

# Section B – Executive Summary
_render_executive_summary(data)

st.divider()

# Section C – Prioritization Overview
_render_prioritization_overview(data)

st.divider()

# Section D – Action Details
_render_action_details(data)

st.divider()

# Section E – Strategic Synthesis
_render_strategic_synthesis(data)

st.divider()

# Section F – Export
_render_export_section(data)

st.divider()

# Navigation
_render_navigation()

# ------------------------------------------------------------------------------
# FOOTER
# ------------------------------------------------------------------------------
render_footer(
    product_name="JESA DMAT",
    version="v1.0.0",
    organization="JESA · ENSAM Casablanca",
    tagline="Internship Project · Digital Transformation & Industry 5.0",
    links=[
        {"label": "JESA", "url": "https://www.jesa.ma"},
        {"label": "ENSAM Casablanca", "url": "https://ensam-casablanca.ma"},
    ],
    align="center",
    compact=False,
    show_divider=True,
)
