"""
Professional PDF exports for JESA DMAT.

This module now ONLY generates the short Score Summary (2 pages).
The Full Report (comprehensive) is generated by exports.report.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.utils import ImageReader

from config import settings
from utils.file_manager import ensure_directory, build_output_path
from utils.helpers import translate_entity_name


logger = logging.getLogger(__name__)


# ------------------------------------------------------------------------------
# Brand / Palette
# ------------------------------------------------------------------------------

JESA_GREEN = colors.HexColor("#007A4D")
JESA_DARK = colors.HexColor("#173F35")
JESA_LIGHT = colors.HexColor("#E8F3EF")

ENSAM_BLUE = colors.HexColor("#0057A8")

WHITE = colors.white
BLACK = colors.black

GREY_100 = colors.HexColor("#F7F9F8")
GREY_200 = colors.HexColor("#E9EEEC")
GREY_400 = colors.HexColor("#B8C4BF")
GREY_600 = colors.HexColor("#5B6863")
GREY_800 = colors.HexColor("#25322E")

CRITICAL_RED = colors.HexColor("#C62828")
HIGH_ORANGE = colors.HexColor("#EF6C00")
MEDIUM_YELLOW = colors.HexColor("#F9A825")
LOW_BLUE = colors.HexColor("#1976D2")
VERY_LOW_GREY = colors.HexColor("#78909C")


PRIORITY_COLORS = {
    "Critical": CRITICAL_RED,
    "High": HIGH_ORANGE,
    "Medium": MEDIUM_YELLOW,
    "Low": LOW_BLUE,
    "Very Low": VERY_LOW_GREY,
}


# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

def _get(
    obj: Any,
    key: str,
    default: Any = None,
) -> Any:
    """
    Read a value from either:
        - a Mapping/dictionary
        - an object attribute
    """

    if obj is None:
        return default

    if isinstance(obj, Mapping):
        return obj.get(key, default)

    return getattr(obj, key, default)


def _safe_str(
    value: Any,
    default: str = "",
) -> str:
    if value is None:
        return default

    return str(value)


def _safe_float(
    value: Any,
    default: float = 0.0,
) -> float:
    try:
        return (
            float(value)
            if value is not None
            else default
        )
    except (TypeError, ValueError):
        return default


def _format_number(
    value: Any,
    decimals: int = 1,
) -> str:
    if value is None:
        return "—"

    try:
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return str(value)


def _normalize_priority(
    priority: Any,
) -> str:
    if priority is None:
        return ""

    mapping = {
        "critical": "Critical",
        "critique": "Critical",

        "high": "High",
        "haute": "High",

        "medium": "Medium",
        "moyenne": "Medium",

        "low": "Low",
        "faible": "Low",

        "very low": "Very Low",
        "très faible": "Very Low",
        "tres faible": "Very Low",
    }

    normalized = str(priority).strip().lower()

    return mapping.get(
        normalized,
        str(priority),
    )


def _priority_color(
    priority: Any,
) -> colors.Color:
    return PRIORITY_COLORS.get(
        _normalize_priority(priority),
        GREY_600,
    )


def _as_list(
    value: Any,
) -> List[Any]:
    if value is None:
        return []

    if isinstance(value, list):
        return value

    if isinstance(value, tuple):
        return list(value)

    if isinstance(value, Mapping):
        return list(value.values())

    return [value]


def _escape_xml(
    value: Any,
    default: Any = None,
) -> str:
    text = _safe_str(
        value,
        _safe_str(default),
    )

    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


# ------------------------------------------------------------------------------
# Logo helpers
# ------------------------------------------------------------------------------

def _find_logo(
    directory: Path,
    candidates: List[str],
) -> Optional[Path]:
    """
    Find a logo using exact filename matching first,
    followed by case-insensitive matching.
    """

    if not directory.exists():
        return None

    if not directory.is_dir():
        return None

    # Exact match
    for filename in candidates:

        path = directory / filename

        if path.exists() and path.is_file():
            return path

    # Case-insensitive fallback
    candidate_names = {
        name.lower()
        for name in candidates
    }

    try:

        for path in directory.iterdir():

            if (
                path.is_file()
                and path.name.lower()
                in candidate_names
            ):
                return path

    except OSError:
        return None

    return None


# ------------------------------------------------------------------------------
# Base PDF Exporter
# ------------------------------------------------------------------------------

class _BasePDFExporter:
    """
    Shared styles, logo discovery and page header/footer
    for PDF exports.
    """

    def __init__(
        self,
        config: Optional[Mapping[str, Any]] = None,
    ):
        self.config = dict(config or {})

        self.decimal_precision = self.config.get(
            "decimal_precision",
            getattr(
                settings,
                "SCORE_DECIMAL_PRECISION",
                1,
            ),
        )

        self.generated_at = datetime.now()

        # Metadata explicitly supplied by the caller (for example from
        # the New Assessment page). Keep it separate from aggregation
        # results so export-only metadata is not lost.
        self.metadata: Dict[str, Any] = {}

        self.styles = self._build_styles()

        self._logo_paths = self._locate_logos()

    # ------------------------------------------------------------------
    # Styles
    # ------------------------------------------------------------------

    def _build_styles(self):
        styles = getSampleStyleSheet()

        return {
            "title": ParagraphStyle(
                "ReportTitle",
                parent=styles["Title"],
                fontName="Helvetica-Bold",
                fontSize=17,
                leading=20,
                textColor=JESA_DARK,
                alignment=TA_CENTER,
                spaceAfter=4,
            ),

            "subtitle": ParagraphStyle(
                "ReportSubtitle",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=7.5,
                leading=9,
                textColor=GREY_600,
                alignment=TA_CENTER,
                spaceAfter=5,
            ),

            "h1": ParagraphStyle(
                "SectionTitle",
                parent=styles["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=13,
                leading=15,
                textColor=JESA_DARK,
                spaceBefore=0,
                spaceAfter=5,
            ),

            "h2": ParagraphStyle(
                "SubSectionTitle",
                parent=styles["Heading2"],
                fontName="Helvetica-Bold",
                fontSize=9,
                leading=11,
                textColor=JESA_DARK,
                spaceBefore=4,
                spaceAfter=3,
            ),

            "body": ParagraphStyle(
                "Body",
                parent=styles["BodyText"],
                fontName="Helvetica",
                fontSize=7,
                leading=9,
                textColor=GREY_800,
                spaceAfter=3,
            ),

            "small": ParagraphStyle(
                "Small",
                parent=styles["BodyText"],
                fontName="Helvetica",
                fontSize=6,
                leading=7,
                textColor=GREY_600,
            ),

            "kpi": ParagraphStyle(
                "KPI",
                parent=styles["BodyText"],
                fontName="Helvetica-Bold",
                fontSize=17,
                leading=19,
                textColor=JESA_DARK,
                alignment=TA_CENTER,
            ),

            "kpi_label": ParagraphStyle(
                "KPILabel",
                parent=styles["BodyText"],
                fontName="Helvetica-Bold",
                fontSize=6.5,
                leading=8,
                textColor=GREY_600,
                alignment=TA_CENTER,
            ),

            "table_header": ParagraphStyle(
                "TableHeader",
                parent=styles["BodyText"],
                fontName="Helvetica-Bold",
                fontSize=5.8,
                leading=7,
                textColor=WHITE,
                alignment=TA_CENTER,
            ),

            "table_cell": ParagraphStyle(
                "TableCell",
                parent=styles["BodyText"],
                fontName="Helvetica",
                fontSize=5.8,
                leading=7,
                textColor=GREY_800,
            ),

            "table_cell_bold": ParagraphStyle(
                "TableCellBold",
                parent=styles["BodyText"],
                fontName="Helvetica-Bold",
                fontSize=5.8,
                leading=7,
                textColor=GREY_800,
            ),
        }

    # ------------------------------------------------------------------
    # Logo discovery
    # ------------------------------------------------------------------

    def _locate_logos(
        self,
    ) -> Dict[str, Optional[Path]]:
        """
        Locate JESA and ENSAM logos from common project directories.
        """

        possible_bases = [
            Path(__file__).resolve().parents[1],
            Path.cwd(),
        ]

        try:
            possible_bases.insert(
                0,
                Path(
                    settings.backend.BASE_DIR
                ),
            )
        except Exception:
            pass

        logo_directories: List[Path] = []

        for base in possible_bases:

            logo_directories.extend(
                [
                    base / "assets" / "logos",
                    base / "assets" / "logo",
                    base / "assets",
                ]
            )

        jesa_path: Optional[Path] = None
        ensam_path: Optional[Path] = None

        jesa_candidates = [
            "logo_jesa.png",
            "jesa_logo.png",
            "JESA_logo.png",
            "jesa.png",
            "JESA.png",
            "logo_jesa.jpg",
            "jesa_logo.jpg",
            "JESA_logo.jpg",
        ]

        ensam_candidates = [
            "logo_ensam.png",
            "ensam_logo.png",
            "ENSAM_logo.png",
            "ensam.png",
            "ENSAM.png",
            "logo_ensam.jpg",
            "ensam_logo.jpg",
            "ENSAM_logo.jpg",
        ]

        for directory in logo_directories:

            if not directory.exists():
                continue

            if jesa_path is None:
                jesa_path = _find_logo(
                    directory,
                    jesa_candidates,
                )

            if ensam_path is None:
                ensam_path = _find_logo(
                    directory,
                    ensam_candidates,
                )

            if (
                jesa_path is not None
                and ensam_path is not None
            ):
                break

        # Final direct lookup
        if (
            jesa_path is None
            or ensam_path is None
        ):

            direct_path = (
                Path(__file__).resolve().parents[1]
                / "assets"
                / "logos"
            )

            if direct_path.exists():

                if jesa_path is None:
                    jesa_path = _find_logo(
                        direct_path,
                        jesa_candidates,
                    )

                if ensam_path is None:
                    ensam_path = _find_logo(
                        direct_path,
                        ensam_candidates,
                    )

        logger.info(
            "JESA logo path: %s",
            jesa_path,
        )

        logger.info(
            "ENSAM logo path: %s",
            ensam_path,
        )

        return {
            "jesa": jesa_path,
            "ensam": ensam_path,
        }

    # ------------------------------------------------------------------
    # Header / Footer
    # ------------------------------------------------------------------

    def _draw_header_footer(
        self,
        canvas,
        doc,
        title_prefix: str = "",
    ):
        """
        Draw the page header/footer.

        IMPORTANT:
        The logos occupy the upper header area.
        The textual header is deliberately positioned BELOW
        the logos so that the two elements never overlap.
        """

        canvas.saveState()

        width, height = A4

        # ==============================================================
        # HEADER GEOMETRY
        # ==============================================================

        left_margin = 12 * mm
        right_margin = 12 * mm

        # Logo dimensions
        logo_width = 80
        logo_height = 40

        # Logo bottom Y position
        logo_y = height - 16 * mm

        # Text is deliberately BELOW the logos.
        text_y = height - 24 * mm

        # Separator is below header text.
        separator_y = height - 27 * mm

        # ==============================================================
        # JESA LOGO
        # ==============================================================

        if self._logo_paths.get("jesa"):

            try:

                img = ImageReader(
                    str(
                        self._logo_paths["jesa"]
                    )
                )

                canvas.drawImage(
                    img,
                    left_margin,
                    logo_y,
                    width=logo_width,
                    height=logo_height,
                    preserveAspectRatio=True,
                    mask="auto",
                )

            except Exception as exc:

                logger.warning(
                    "Could not draw JESA logo: %s",
                    exc,
                )

        # ==============================================================
        # ENSAM LOGO
        # ==============================================================

        if self._logo_paths.get("ensam"):

            try:

                img = ImageReader(
                    str(
                        self._logo_paths["ensam"]
                    )
                )

                canvas.drawImage(
                    img,
                    width - 92 * mm,
                    logo_y,
                    width=logo_width,
                    height=logo_height,
                    preserveAspectRatio=True,
                    mask="auto",
                )

            except Exception as exc:

                logger.warning(
                    "Could not draw ENSAM logo: %s",
                    exc,
                )

        # ==============================================================
        # HEADER TEXT
        # ==============================================================
        #
        # THIS IS THE FIX:
        #
        # Previously:
        #     height - 9 mm
        #
        # which placed the text alongside/over the logos.
        #
        # Now:
        #     height - 24 mm
        #
        # which places the text below the logos.
        # ==============================================================

        canvas.setFont(
            "Helvetica-Bold",
            6.5,
        )

        canvas.setFillColor(
            JESA_DARK
        )

        canvas.drawString(
            left_margin,
            text_y,
            "JESA DMAT",
        )

        canvas.setFont(
            "Helvetica",
            6.5,
        )

        canvas.setFillColor(
            GREY_600
        )

        header_right_text = (
            f"{title_prefix} — "
            "Industrial Digital Maturity Assessment"
        )

        canvas.drawRightString(
            width - right_margin,
            text_y,
            header_right_text,
        )

        # ==============================================================
        # HEADER SEPARATOR
        # ==============================================================

        canvas.setStrokeColor(
            GREY_200
        )

        canvas.setLineWidth(
            0.5
        )

        canvas.line(
            left_margin,
            separator_y,
            width - right_margin,
            separator_y,
        )

        # ==============================================================
        # FOOTER
        # ==============================================================

        canvas.setStrokeColor(
            GREY_200
        )

        canvas.line(
            left_margin,
            8 * mm,
            width - right_margin,
            8 * mm,
        )

        canvas.setFont(
            "Helvetica",
            5.8,
        )

        canvas.setFillColor(
            GREY_600
        )

        canvas.drawString(
            left_margin,
            4.5 * mm,
            "JESA DMAT • Digital Maturity Assessment",
        )

        canvas.drawRightString(
            width - right_margin,
            4.5 * mm,
            f"Page {doc.page}",
        )

        canvas.restoreState()


# ------------------------------------------------------------------------------
# PDF Score Summary
# ------------------------------------------------------------------------------

class PDFScoreSummaryExporter(
    _BasePDFExporter
):
    """
    Generates a concise 2-page PDF with:
        - DMI
        - Pillars
        - Dimensions
        - Gaps
        - TPI
        - Priorities
    """

    def export(
        self,
        aggregation_results: Dict[str, Any],
        gap_results: Optional[List[Any]] = None,
        tpi_results: Optional[List[Any]] = None,
        priority_results: Optional[List[Any]] = None,
        output_path: Optional[Path] = None,
        assessment_id: Optional[str] = None,
    ) -> Path:

        if output_path is None:

            suffix = (
                f"_{assessment_id}"
                if assessment_id
                else ""
            )

            filename = (
                "JESA_DMAT_Score_Summary"
                f"{suffix}.pdf"
            )

            output_path = build_output_path(
                filename
            )

        output_path = Path(
            output_path
        )

        ensure_directory(
            output_path.parent
        )

        # ==============================================================
        # IMPORTANT:
        # The header is now taller because the text is under the logos.
        # Therefore topMargin is increased.
        # ==============================================================

        doc = BaseDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=12 * mm,
            leftMargin=12 * mm,
            topMargin=31 * mm,
            bottomMargin=14 * mm,
            title="JESA DMAT Score Summary",
            author="JESA DMAT",
            subject=(
                "Industrial Digital "
                "Maturity Assessment"
            ),
        )

        frame = Frame(
            doc.leftMargin,
            doc.bottomMargin,
            doc.width,
            doc.height,
            id="main_frame",
        )

        page_template = PageTemplate(
            id="ScoreSummary",
            frames=frame,
            onPage=lambda canvas, doc: (
                self._draw_header_footer(
                    canvas,
                    doc,
                    "Score Summary",
                )
            ),
        )

        doc.addPageTemplates(
            [page_template]
        )

        story: List[Any] = []

        # ==============================================================
        # PAGE 1
        # ==============================================================

        self._build_page1(
            story,
            aggregation_results,
            assessment_id,
        )

        story.append(
            PageBreak()
        )

        # ==============================================================
        # PAGE 2
        # ==============================================================

        self._build_page2(
            story,
            aggregation_results,
            gap_results,
            tpi_results,
            priority_results,
        )

        doc.build(story)

        logger.info(
            "Score Summary PDF generated: %s",
            output_path,
        )

        return output_path

    # ------------------------------------------------------------------
    # Page 1
    # ------------------------------------------------------------------

    def _build_page1(
        self,
        story,
        results,
        assessment_id,
    ):
        # Preserve explicit export metadata first, then use any metadata
        # embedded in aggregation results as a fallback. This prevents
        # assessment_date, evaluator, and site_id from being lost when
        # the score summary is generated.
        metadata = dict(self.metadata or {})
        embedded_metadata = results.get("metadata", {}) or {}

        if isinstance(embedded_metadata, Mapping):
            for key, value in embedded_metadata.items():
                if key not in metadata or metadata.get(key) in (None, ""):
                    metadata[key] = value

        site_name = metadata.get(
            "plant",
            metadata.get(
                "site_name",
                "Industrial Plant",
            ),
        )

        dmi = results.get(
            "dmi"
        )

        dmi_score = _get(
            dmi,
            "score",
            results.get(
                "dmi_score"
            ),
        )

        dmi_level = _get(
            dmi,
            "level_name",
            results.get(
                "dmi_level_name",
                results.get(
                    "dmi_level",
                    "—",
                ),
            ),
        )

        resolved_assessment_id = (
            assessment_id
            or metadata.get(
                "assessment_id",
                "N/A",
            )
        )

        # --------------------------------------------------------------
        # Title
        # --------------------------------------------------------------

        story.append(
            Paragraph(
                "DIGITAL MATURITY SCORE SUMMARY",
                self.styles["title"],
            )
        )

        story.append(
            Paragraph(
                (
                    f"{_escape_xml(site_name)} "
                    f"• Assessment: "
                    f"{_escape_xml(resolved_assessment_id)}"
                ),
                self.styles["subtitle"],
            )
        )

        # Compact metadata line. The values are already collected on the
        # New Assessment page; this only makes them visible in the Score
        # Summary without changing any scoring or report calculations.
        metadata_line = (
            f"Site ID: {_escape_xml(metadata.get('site_id', '—') or '—')} "
            f"• Assessment Date: {_escape_xml(metadata.get('assessment_date', '—') or '—')} "
            f"• Evaluator: {_escape_xml(metadata.get('evaluator', '—') or '—')}"
        )

        story.append(
            Paragraph(
                metadata_line,
                self.styles["small"],
            )
        )

        story.append(
            Spacer(
                1,
                1.5 * mm,
            )
        )

        # --------------------------------------------------------------
        # KPI TABLE
        # --------------------------------------------------------------

        kpi_data = [
            [
                Paragraph(
                    _format_number(
                        dmi_score,
                        self.decimal_precision,
                    ),
                    self.styles["kpi"],
                ),
                Paragraph(
                    _escape_xml(
                        dmi_level,
                        "—",
                    ),
                    self.styles["kpi"],
                ),
            ],
            [
                Paragraph(
                    "DIGITAL MATURITY INDEX",
                    self.styles["kpi_label"],
                ),
                Paragraph(
                    "MATURITY LEVEL",
                    self.styles["kpi_label"],
                ),
            ],
        ]

        kpi_table = Table(
            kpi_data,
            colWidths=[
                85 * mm,
                85 * mm,
            ],
        )

        kpi_table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, -1),
                        GREY_100,
                    ),
                    (
                        "BOX",
                        (0, 0),
                        (-1, -1),
                        0.8,
                        JESA_GREEN,
                    ),
                    (
                        "INNERGRID",
                        (0, 0),
                        (-1, -1),
                        0.4,
                        GREY_200,
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, 0),
                        8,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, 0),
                        8,
                    ),
                ]
            )
        )

        story.append(
            kpi_table
        )

        story.append(
            Spacer(
                1,
                4 * mm,
            )
        )

        # --------------------------------------------------------------
        # PILLAR SCORES
        # --------------------------------------------------------------

        story.append(
            Paragraph(
                "1. Pillar Scores",
                self.styles["h1"],
            )
        )

        pillars = results.get(
            "pillars",
            {},
        )

        pillar_iter = (
            pillars.values()
            if isinstance(
                pillars,
                Mapping,
            )
            else _as_list(pillars)
        )

        rows = [
            [
                Paragraph(
                    "Pillar",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Score",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Maturity",
                    self.styles["table_header"],
                ),
            ]
        ]

        for res in pillar_iter:

            entity_id = _get(
                res,
                "entity_id",
            )

            entity_name = _get(
                res,
                "entity_name",
                "—",
            )

            translated_name = (
                translate_entity_name(
                    entity_id,
                    entity_name,
                )
            )

            rows.append(
                [
                    Paragraph(
                        _escape_xml(
                            translated_name
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _format_number(
                            _get(
                                res,
                                "score",
                            ),
                            self.decimal_precision,
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _escape_xml(
                            _get(
                                res,
                                "level_name",
                                "—",
                            )
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                ]
            )

        if len(rows) == 1:

            rows.append(
                [
                    Paragraph(
                        "No pillar results",
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    "",
                    "",
                ]
            )

        tab = Table(
            rows,
            colWidths=[
                95 * mm,
                40 * mm,
                35 * mm,
            ],
            repeatRows=1,
        )

        tab.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        JESA_GREEN,
                    ),
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.35,
                        GREY_200,
                    ),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [
                            WHITE,
                            GREY_100,
                        ],
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "ALIGN",
                        (0, 0),
                        (0, -1),
                        "LEFT",
                    ),
                    (
                        "ALIGN",
                        (1, 1),
                        (-1, -1),
                        "CENTER",
                    ),
                ]
            )
        )

        story.append(
            tab
        )

        story.append(
            Spacer(
                1,
                4 * mm,
            )
        )

        # --------------------------------------------------------------
        # DIMENSION SCORES
        # --------------------------------------------------------------

        story.append(
            Paragraph(
                "2. Dimension Scores",
                self.styles["h1"],
            )
        )

        dimensions = results.get(
            "dimensions",
            {},
        )

        dim_iter = (
            dimensions.values()
            if isinstance(
                dimensions,
                Mapping,
            )
            else _as_list(dimensions)
        )

        rows_dim = [
            [
                Paragraph(
                    "ID",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Dimension",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Score",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Level",
                    self.styles["table_header"],
                ),
            ]
        ]

        for res in dim_iter:

            entity_id = _get(
                res,
                "entity_id",
                "—",
            )

            entity_name = _get(
                res,
                "entity_name",
                "—",
            )

            translated_name = (
                translate_entity_name(
                    entity_id,
                    entity_name,
                )
            )

            rows_dim.append(
                [
                    Paragraph(
                        _escape_xml(
                            entity_id
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _escape_xml(
                            translated_name
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _format_number(
                            _get(
                                res,
                                "score",
                            ),
                            self.decimal_precision,
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _escape_xml(
                            _get(
                                res,
                                "level_name",
                                "—",
                            )
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                ]
            )

        if len(rows_dim) == 1:

            rows_dim.append(
                [
                    "",
                    Paragraph(
                        "No dimensions",
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    "",
                    "",
                ]
            )

        tab_dim = Table(
            rows_dim,
            colWidths=[
                20 * mm,
                85 * mm,
                25 * mm,
                30 * mm,
            ],
            repeatRows=1,
        )

        tab_dim.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        JESA_GREEN,
                    ),
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.35,
                        GREY_200,
                    ),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [
                            WHITE,
                            GREY_100,
                        ],
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "ALIGN",
                        (0, 0),
                        (0, -1),
                        "CENTER",
                    ),
                    (
                        "ALIGN",
                        (1, 0),
                        (1, -1),
                        "LEFT",
                    ),
                    (
                        "ALIGN",
                        (2, 1),
                        (-1, -1),
                        "CENTER",
                    ),
                ]
            )
        )

        story.append(
            tab_dim
        )

    # ------------------------------------------------------------------
    # Page 2
    # ------------------------------------------------------------------

    def _build_page2(
        self,
        story,
        results,
        gap_results,
        tpi_results,
        priority_results,
    ):
        del results
        del priority_results

        story.append(
            Paragraph(
                "3. Gap & Priority Analysis",
                self.styles["h1"],
            )
        )

        # ==============================================================
        # GAP SCORES
        # ==============================================================

        story.append(
            Paragraph(
                "Gap Scores",
                self.styles["h2"],
            )
        )

        gap_rows = [
            [
                Paragraph(
                    "Entity",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Type",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Current",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Target",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Gap",
                    self.styles["table_header"],
                ),
            ]
        ]

        for gap in gap_results or []:

            entity_id = _get(
                gap,
                "entity_id",
            )

            entity_name = _get(
                gap,
                "entity_name",
                "—",
            )

            translated_name = (
                translate_entity_name(
                    entity_id,
                    entity_name,
                )
            )

            gap_rows.append(
                [
                    Paragraph(
                        _escape_xml(
                            translated_name
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _escape_xml(
                            _get(
                                gap,
                                "entity_type",
                                "—",
                            )
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _format_number(
                            _get(
                                gap,
                                "current_score",
                            ),
                            1,
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _format_number(
                            _get(
                                gap,
                                "target_score",
                            ),
                            1,
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _format_number(
                            _get(
                                gap,
                                "gap",
                            ),
                            1,
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                ]
            )

        if len(gap_rows) == 1:

            gap_rows.append(
                [
                    Paragraph(
                        "No gaps",
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    "",
                    "",
                    "",
                    "",
                ]
            )

        gap_tab = Table(
            gap_rows,
            colWidths=[
                60 * mm,
                35 * mm,
                25 * mm,
                25 * mm,
                20 * mm,
            ],
            repeatRows=1,
        )

        gap_tab.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        JESA_GREEN,
                    ),
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.35,
                        GREY_200,
                    ),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [
                            WHITE,
                            GREY_100,
                        ],
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "ALIGN",
                        (0, 0),
                        (0, -1),
                        "LEFT",
                    ),
                    (
                        "ALIGN",
                        (2, 1),
                        (-1, -1),
                        "CENTER",
                    ),
                ]
            )
        )

        story.append(
            gap_tab
        )

        story.append(
            Spacer(
                1,
                3 * mm,
            )
        )

        # ==============================================================
        # TPI
        # ==============================================================

        story.append(
            Paragraph(
                "Transformation Priority Index (TPI)",
                self.styles["h2"],
            )
        )

        sorted_tpi = sorted(
            tpi_results or [],
            key=lambda x: -_safe_float(
                _get(
                    x,
                    "tpi_score",
                    0,
                )
            ),
        )

        tpi_rows = [
            [
                Paragraph(
                    "#",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Dimension",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "TPI",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Gap",
                    self.styles["table_header"],
                ),
                Paragraph(
                    "Priority",
                    self.styles["table_header"],
                ),
            ]
        ]

        for rank, item in enumerate(
            sorted_tpi,
            1,
        ):

            priority = _normalize_priority(
                _get(
                    item,
                    "priority_category",
                    _get(
                        item,
                        "priority",
                        "",
                    ),
                )
            )

            dimension_id = _get(
                item,
                "dimension_id",
            )

            dimension_name = _get(
                item,
                "dimension_name",
                "—",
            )

            translated_name = (
                translate_entity_name(
                    dimension_id,
                    dimension_name,
                )
            )

            tpi_rows.append(
                [
                    Paragraph(
                        str(rank),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _escape_xml(
                            translated_name
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _format_number(
                            _get(
                                item,
                                "tpi_score",
                            ),
                            1,
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _format_number(
                            _get(
                                item,
                                "gap",
                            ),
                            1,
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    Paragraph(
                        _escape_xml(
                            priority or "—"
                        ),
                        self.styles[
                            "table_cell"
                        ],
                    ),
                ]
            )

        if len(tpi_rows) == 1:

            tpi_rows.append(
                [
                    "",
                    Paragraph(
                        "No TPI",
                        self.styles[
                            "table_cell"
                        ],
                    ),
                    "",
                    "",
                    "",
                ]
            )

        tpi_tab = Table(
            tpi_rows,
            colWidths=[
                12 * mm,
                85 * mm,
                25 * mm,
                25 * mm,
                25 * mm,
            ],
            repeatRows=1,
            hAlign="CENTER",
        )

        tpi_commands = [
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                JESA_GREEN,
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.35,
                GREY_200,
            ),
            (
                "ROWBACKGROUNDS",
                (0, 1),
                (-1, -1),
                [
                    WHITE,
                    GREY_100,
                ],
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE",
            ),
            (
                "ALIGN",
                (0, 0),
                (0, -1),
                "CENTER",
            ),
            (
                "ALIGN",
                (2, 1),
                (-1, -1),
                "CENTER",
            ),
        ]

        # Priority colors
        for index, item in enumerate(
            sorted_tpi,
            1,
        ):

            priority = _normalize_priority(
                _get(
                    item,
                    "priority_category",
                    _get(
                        item,
                        "priority",
                        "",
                    ),
                )
            )

            if priority:

                tpi_commands.append(
                    (
                        "BACKGROUND",
                        (4, index),
                        (4, index),
                        _priority_color(
                            priority
                        ),
                    )
                )

                if priority != "Medium":

                    tpi_commands.append(
                        (
                            "TEXTCOLOR",
                            (4, index),
                            (4, index),
                            WHITE,
                        )
                    )

        tpi_tab.setStyle(
            TableStyle(
                tpi_commands
            )
        )

        story.append(
            tpi_tab
        )

        story.append(
            Spacer(
                1,
                3 * mm,
            )
        )

        story.append(
            Paragraph(
                (
                    "This document presents only the "
                    "numerical scores. Detailed "
                    "recommendations and roadmap are "
                    "available in the Full Report."
                ),
                self.styles["small"],
            )
        )


# ------------------------------------------------------------------------------
# Public utility
# ------------------------------------------------------------------------------

def export_score_summary(
    aggregation_results: Dict[str, Any],
    gap_results: Optional[List[Any]] = None,
    tpi_results: Optional[List[Any]] = None,
    priority_results: Optional[List[Any]] = None,
    output_path: Optional[Path] = None,
    assessment_id: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> Path:
    """
    Public entry point used by the application
    to generate the short Score Summary PDF.
    """

    exporter = PDFScoreSummaryExporter()

    if metadata:
        exporter.metadata = metadata

    return exporter.export(
        aggregation_results=aggregation_results,
        gap_results=gap_results,
        tpi_results=tpi_results,
        priority_results=priority_results,
        output_path=output_path,
        assessment_id=assessment_id,
    )